version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db

  api-nodejs:
    build: ./nodejs
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydb
    env_file:
      - .env

  frontend:
    build: ./react
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api-nodejs
