name: Build, Test and Deploy React Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
          cd react
          npm ci
          npm test
      - name: Build and docs
        run: |
          cd react
          npm run jsdoc
          npm run build --if-present
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Docker containers mangodb - nodejs
      - name: Build the stack mangodb - nodejs
        run: docker-compose -f docker-compose-nodejs.yml up
      - name: Run e2e tests with cypress
        run: |
          cd ./react
          npm run cypress
      - name: Stop the stack mangodb - nodejs
        run: docker-compose -f docker-compose-nodejs.yml down

      # Docker containers mysql - python
      - name: Build the stack mysql - python
        run: docker-compose -f docker-compose-python.yml up
      - name: Run e2e tests with cypress
        run: |
          cd ./react
          npm run cypress
      - name: Stop the stack mysql - python
        run: docker-compose -f docker-compose-python down
