name: Build, Test and Deploy React Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd react
          npm ci
      - name: Run tests
        run: |
          cd react
          npm test
      - name: Build React application
        run: |
          cd react
          npm run build

  docker_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker-compose build
      - name: Start Docker containers
        run: docker-compose up -d
      - name: Run tests inside Docker containers
        run: |
          docker-compose exec -T api-nodejs sh -c "cd /app && npm test"
          docker-compose exec -T api-python sh -c "cd /app && python -m unittest discover tests/"
      - name: Stop Docker containers
        run: docker-compose down

  integration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker-compose build
      - name: Start Docker containers
        run: docker-compose up -d
      - name: Run integration tests
        run: |
          cd react
          npm ci
          npm run test:integration
      - name: Stop Docker containers
        run: docker-compose down
